name: Main

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Load super-linter env variables
        run: |
          cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint code base
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Start server
        run:
          python echo.py &

      - name: Run tests
        run:
          python -m pytest test.py
